<?xml version="1.0" encoding="utf-8" standalone="yes"?>

    <!DOCTYPE libreria[

		<!ELEMENT libreria (libro+)>
		<!ELEMENT libro (titulo, autor, editorial)>
		<!ELEMENT titulo (#PCDATA)>
		<!ELEMENT autor (#PCDATA)>
        <!ELEMENT editorial (#PCDATA)>	

	]>

<libreria>
	<libro>
		<titulo>Don Quijote</titulo>
		<autor>Miguel de Cervantes</autor>
        <editorial>La Mancha</editorial>
	</libro>
	<libro>
		<titulo>La vida es sue√±o</titulo>
		<autor>Calderon de la Barca</autor>
        <editorial>Mil Editoriales</editorial>
	</libro>
</libreria>