=== RubenGonz/rubenGonzalezRodriguezLND/TareasDossieres/Unidad7/PracticaFinal/PracticaFinal.xsd
<?xml version="1.0"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
targetNamespace="http://www.misitio.com"
xmlns="http://www.misitio.com" 
elementFormDefault="qualified">

    <xs:element name="PracticaFinal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ClinicaVeterinaria" type="tipoClinicaVeterinaria" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="tipoClinicaVeterinaria">
        <xs:sequence>
            <xs:element name="cliente" type="tipoPersona" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attribute name="codigo" type="xs:string" use="required" />
    </xs:complexType>

    <xs:complexType name="tipoPersona">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="apellido" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="animal" type="tipoAnimal" minOccurs="1" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="tipoAnimal">
        <xs:choice>
            <xs:element name="perro" type="CaracteristicasAnimal"/>
            <xs:element name="gato" type="CaracteristicasAnimal"/>
            <xs:element name="reptil" type="CaracteristicasAnimal"/>
        </xs:choice>
    </xs:complexType>

    <xs:complexType name="CaracteristicasAnimal">
        <xs:sequence>
            <xs:element name="nombre" type="xs:string" />
            <xs:element name="edad" type="tipoEdad" />
            <xs:element name="raza" type="xs:string" />
            <xs:element name="sexo" type="tipoSexo" default="M" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="tipoEdad">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
            <xs:maxInclusive value="15" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipoSexo">
        <xs:restriction base="xs:string">
            <xs:enumeration value="M" />
            <xs:enumeration value="H" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== RubenGonz/rubenGonzalezRodriguezLND/TareasDossieres/Unidad7/PracticaFinal/PracticaFinal.xml
<?xml version="1.0"?>

<PracticaFinal xmlns="http://www.misitio.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:schemaLocation="http://www.misitio.com PracticaFinal.xsd">

    <ClinicaVeterinaria codigo="123456">
        
        <cliente>
            <nombre>Ruben</nombre>
            <apellido>Gonzalez Rodriguez</apellido>
            <animal>
                <gato>
                    <nombre>Mora</nombre>
                    <edad>13</edad>
                    <raza>Callejero</raza>
                    <sexo>H</sexo>
                </gato>
            </animal>
        </cliente>

        <cliente>
            <nombre>Natalia</nombre>
            <apellido>Hernandez Diaz</apellido>
            <animal>
                <perro>
                    <nombre>Rudolf</nombre>
                    <edad>7</edad>
                    <raza>Golden retriever</raza>
                    <sexo>M</sexo>
                </perro>
            </animal>
        </cliente>

        <cliente>
            <nombre>Magali</nombre>
            <apellido>Morales Rodriguez</apellido>
            <animal>
                <reptil>
                    <nombre>Lisa</nombre>
                    <edad>5</edad>
                    <raza>Iguana</raza>
                    <sexo>H</sexo>
                </reptil>
            </animal>
        </cliente>

    </ClinicaVeterinaria>

</PracticaFinal>
